let er1 = new RegExp ('abc');
let er2 = new RegExp ('ab+c');
let er3 = new RegExp ('ab*c');
let er4 = new RegExp ('7');
let er5 = new RegExp ('7{3}');
let er6 = new RegExp ('(abc)+');
let er7 = new RegExp ('[A-Z]{0,1}[0-9]{1,8}');
let er8 = new RegExp ('\w*.(com)|(es)');
console.log (er1.test("abc"));
console.log (er1.test("abcd"));
console.log (er2.test("abbbc"));
console.log (er3.test("ac"));
console.log (er4.test("8"));
console.log (er5.test("7777"));
console.log (er5.test("77"));
console.log (er5.test("77"));
console.log (er6.test("abcabc"));
console.log (er7.test("53130984"));
console.log (er7.test("P5313098"));
console.log (er8.test("amigos.es"));
console.log (er8.test("vinitos.com"));
